package ru.reu_intro;

import java.util.ArrayList;
import java.util.Arrays;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;

public class attendance extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel_1;
	@AutoGenerated
	private Table table_1;
	@AutoGenerated
	private GridLayout gridLayout_2;
	@AutoGenerated
	private Button button_4;
	@AutoGenerated
	private ComboBox comboBox_13;
	@AutoGenerated
	private Label label_16;
	@AutoGenerated
	private ComboBox comboBox_12;
	@AutoGenerated
	private Label label_15;
	@AutoGenerated
	private ComboBox comboBox_11;
	@AutoGenerated
	private Label label_14;
	@AutoGenerated
	private ComboBox comboBox_10;
	@AutoGenerated
	private Label label_13;
	@AutoGenerated
	private Label label_12;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public attendance() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalSplitPanel_1
		horizontalSplitPanel_1 = buildHorizontalSplitPanel_1();
		mainLayout
				.addComponent(horizontalSplitPanel_1, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_1() {
		// common part: create layout
		horizontalSplitPanel_1 = new HorizontalSplitPanel();
		horizontalSplitPanel_1.setImmediate(false);
		horizontalSplitPanel_1.setWidth("100.0%");
		horizontalSplitPanel_1.setHeight("100.0%");
		horizontalSplitPanel_1.setMargin(false);
		
		// gridLayout_2
		gridLayout_2 = buildGridLayout_2();
		horizontalSplitPanel_1.addComponent(gridLayout_2);
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("100.0%");
		table_1.setHeight("100.0%");
		
		tableData.initProperties(table_1, new String[]{"Фамилия", "Предмет", "Количество посещений", "Период"});
		tableData.fillTable(table_1, new String[][]{{"Андреенков Александр Викторович","Информационные системы","29","С 01.09.2013 по 3.10.2013"},{"Иванов Иван Иванович","БД","45","С 01.09.2013 по 3.10.2013"}, {"Андреенков Александр Викторович","Экономика","15","С 01.09.2013 по 3.10.2013"}});
		
		horizontalSplitPanel_1.addComponent(table_1);
		
		return horizontalSplitPanel_1;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_2() {
		// common part: create layout
		gridLayout_2 = new GridLayout();
		gridLayout_2.setImmediate(false);
		gridLayout_2.setWidth("100.0%");
		gridLayout_2.setHeight("100.0%");
		gridLayout_2.setMargin(false);
		gridLayout_2.setColumns(5);
		gridLayout_2.setRows(15);
		
		// label_12
		label_12 = new Label();
		label_12.setImmediate(false);
		label_12.setWidth("-1px");
		label_12.setHeight("-1px");
		label_12.setValue("<h1>Журнал посещений</h1>");
		label_12.setContentMode(3);
		gridLayout_2.addComponent(label_12, 2, 1);
		
		// label_13
		label_13 = new Label();
		label_13.setImmediate(false);
		label_13.setWidth("-1px");
		label_13.setHeight("-1px");
		label_13.setValue("Направление");
		gridLayout_2.addComponent(label_13, 1, 2);
		gridLayout_2.setComponentAlignment(label_13, new Alignment(6));
		
		// comboBox_10
		comboBox_10 = new ComboBox();
		comboBox_10.setImmediate(false);
		comboBox_10.setWidth("232px");
		comboBox_10.setHeight("-1px");
		comboboxData.fillCombobox(comboBox_10, new ArrayList<String>(Arrays.asList("Экономика","Прикладная математика и информатика","Бизнес-информатика")));
		gridLayout_2.addComponent(comboBox_10, 2, 2);
		gridLayout_2.setComponentAlignment(comboBox_10, new Alignment(20));
		
		// label_14
		label_14 = new Label();
		label_14.setImmediate(false);
		label_14.setWidth("-1px");
		label_14.setHeight("-1px");
		label_14.setValue("Курс");
		gridLayout_2.addComponent(label_14, 1, 3);
		gridLayout_2.setComponentAlignment(label_14, new Alignment(6));
		
		// comboBox_11
		comboBox_11 = new ComboBox();
		comboBox_11.setImmediate(false);
		comboBox_11.setWidth("232px");
		comboBox_11.setHeight("-1px");
		comboboxData.fillCombobox(comboBox_11, new ArrayList<String>(Arrays.asList("I курс","II курс","III курс", "IV курс", "V курс")));
		gridLayout_2.addComponent(comboBox_11, 2, 3);
		gridLayout_2.setComponentAlignment(comboBox_11, new Alignment(20));
		
		// label_15
		label_15 = new Label();
		label_15.setImmediate(false);
		label_15.setWidth("-1px");
		label_15.setHeight("-1px");
		label_15.setValue("Группа");
		gridLayout_2.addComponent(label_15, 1, 4);
		gridLayout_2.setComponentAlignment(label_15, new Alignment(6));
		
		// comboBox_12
		comboBox_12 = new ComboBox();
		comboBox_12.setImmediate(false);
		comboBox_12.setWidth("232px");
		comboBox_12.setHeight("-1px");
		comboboxData.fillCombobox(comboBox_12, new ArrayList<String>(Arrays.asList("411","412","413","414", "415", "416")));
		gridLayout_2.addComponent(comboBox_12, 2, 4);
		gridLayout_2.setComponentAlignment(comboBox_12, new Alignment(20));
		
		// label_16
		label_16 = new Label();
		label_16.setImmediate(false);
		label_16.setWidth("-1px");
		label_16.setHeight("-1px");
		label_16.setValue("Дисциплина");
		gridLayout_2.addComponent(label_16, 1, 5);
		gridLayout_2.setComponentAlignment(label_16, new Alignment(6));
		
		// comboBox_13
		comboBox_13 = new ComboBox();
		comboBox_13.setImmediate(false);
		comboBox_13.setWidth("232px");
		comboBox_13.setHeight("-1px");
		comboboxData.fillCombobox(comboBox_13, new ArrayList<String>(Arrays.asList("ПИС","КИС","МБП","Экономика труда", "Маркетинг", "Английский")));
		gridLayout_2.addComponent(comboBox_13, 2, 5);
		gridLayout_2.setComponentAlignment(comboBox_13, new Alignment(20));
		
		// button_4
		button_4 = new Button();
		button_4.setCaption("Скачать журнал посещений (.doc)");
		button_4.setImmediate(true);
		button_4.setWidth("-1px");
		button_4.setHeight("-1px");
		gridLayout_2.addComponent(button_4, 2, 6);
		gridLayout_2.setComponentAlignment(button_4, new Alignment(9));
		
		return gridLayout_2;
	}

}
