package ru.reu_intro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;

public class db extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,40","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":8} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_2;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel_4;
	@AutoGenerated
	private GridLayout gridLayout_2;
	@AutoGenerated
	private Button button_9;
	@AutoGenerated
	private Button button_8;
	@AutoGenerated
	private Button button_7;
	@AutoGenerated
	private Button button_6;
	@AutoGenerated
	private TextField textField_8;
	@AutoGenerated
	private Label label_15;
	@AutoGenerated
	private TextField textField_14;
	@AutoGenerated
	private Label label_14;
	@AutoGenerated
	private TextField textField_13;
	@AutoGenerated
	private Label label_13;
	@AutoGenerated
	private TextField textField_12;
	@AutoGenerated
	private Label label_12;
	@AutoGenerated
	private TextField textField_11;
	@AutoGenerated
	private Label label_11;
	@AutoGenerated
	private TextField textField_10;
	@AutoGenerated
	private Label label_10;
	@AutoGenerated
	private TextField textField_9;
	@AutoGenerated
	private Label label_9;
	@AutoGenerated
	private Table table_1;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel_1;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Button button_4;
	@AutoGenerated
	private Button button_3;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private TextField textField_7;
	@AutoGenerated
	private Label label_7;
	@AutoGenerated
	private TextField textField_6;
	@AutoGenerated
	private Label label_6;
	@AutoGenerated
	private TextField textField_5;
	@AutoGenerated
	private Label label_5;
	@AutoGenerated
	private TextField textField_4;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private TextField textField_3;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private TextField textField_2;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Table table_2;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public db() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet_2
		tabSheet_2 = buildTabSheet_2();
		mainLayout.addComponent(tabSheet_2,
				"right:0.0px;bottom:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_2() {
		// common part: create layout
		tabSheet_2 = new TabSheet();
		tabSheet_2.setImmediate(true);
		tabSheet_2.setWidth("100.0%");
		tabSheet_2.setHeight("100.0%");
		
		// horizontalSplitPanel_1
		horizontalSplitPanel_1 = buildHorizontalSplitPanel_1();
		tabSheet_2.addTab(horizontalSplitPanel_1, "Сотрудники", null);
		
		// horizontalSplitPanel_4
		horizontalSplitPanel_4 = buildHorizontalSplitPanel_4();
		tabSheet_2.addTab(horizontalSplitPanel_4, "Студенты", null);
		
		return tabSheet_2;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_1() {
		// common part: create layout
		horizontalSplitPanel_1 = new HorizontalSplitPanel();
		horizontalSplitPanel_1.setImmediate(false);
		horizontalSplitPanel_1.setWidth("100.0%");
		horizontalSplitPanel_1.setHeight("100.0%");
		horizontalSplitPanel_1.setMargin(false);
		
		// table_2
		table_2 = new Table();
		table_2.setImmediate(false);
		table_2.setWidth("100.0%");
		table_2.setHeight("100.0%");
		horizontalSplitPanel_1.addComponent(table_2);
		

		tableData.initProperties(table_2, new String[]{"ФИО", "Должность", "Ученое звание", "Ученая степень", "e-mail", "Телефон"});
		tableData.fillTable(table_2, new String[][]{{"Рузе Анатолий Иванович","Зам. декана", "Доцент", "Д-р архитектуры", "anatosh@gmail.com", "458-32-44"}, {"Гольнев Виктор Иванович","Преподаватель", "Профессор", "Канд. пед. наук", "anatosh@gmail.com", "458-56-12"},
				{"Воронов Владислав Иванович","Преподаватель", "Член-корреспондент", "Канд. филол. наук", "bosh@gmail.com", "758-32-44"}, {"Князев Максим Евгеньевич","Преподаватель", "Доцент", "Д-р физ.-мат. наук", "vsassh@gmail.com", "458-32-44"}});
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		horizontalSplitPanel_1.addComponent(gridLayout_1);
		
		return horizontalSplitPanel_1;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("100.0%");
		gridLayout_1.setMargin(true);
		gridLayout_1.setRows(35);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("ФИО");
		gridLayout_1.addComponent(label_1, 0, 1);
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("100.0%");
		textField_1.setHeight("-1px");
		gridLayout_1.addComponent(textField_1, 0, 2);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Должность");
		gridLayout_1.addComponent(label_2, 0, 3);
		
		// textField_2
		textField_2 = new TextField();
		textField_2.setImmediate(false);
		textField_2.setWidth("100.0%");
		textField_2.setHeight("-1px");
		gridLayout_1.addComponent(textField_2, 0, 4);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Ученое звание");
		gridLayout_1.addComponent(label_3, 0, 5);
		
		// textField_3
		textField_3 = new TextField();
		textField_3.setImmediate(false);
		textField_3.setWidth("100.0%");
		textField_3.setHeight("-1px");
		gridLayout_1.addComponent(textField_3, 0, 6);
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Ученая степень");
		gridLayout_1.addComponent(label_4, 0, 7);
		
		// textField_4
		textField_4 = new TextField();
		textField_4.setImmediate(false);
		textField_4.setWidth("100.0%");
		textField_4.setHeight("-1px");
		gridLayout_1.addComponent(textField_4, 0, 8);
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("E-mail");
		gridLayout_1.addComponent(label_5, 0, 9);
		
		// textField_5
		textField_5 = new TextField();
		textField_5.setImmediate(false);
		textField_5.setWidth("100.0%");
		textField_5.setHeight("-1px");
		gridLayout_1.addComponent(textField_5, 0, 10);
		
		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("-1px");
		label_6.setHeight("-1px");
		label_6.setValue("Телефон");
		gridLayout_1.addComponent(label_6, 0, 11);
		
		// textField_6
		textField_6 = new TextField();
		textField_6.setImmediate(false);
		textField_6.setWidth("100.0%");
		textField_6.setHeight("-1px");
		gridLayout_1.addComponent(textField_6, 0, 12);
		
		// label_7
		label_7 = new Label();
		label_7.setImmediate(false);
		label_7.setWidth("-1px");
		label_7.setHeight("-1px");
		label_7.setValue("Дополнительная информация");
		gridLayout_1.addComponent(label_7, 0, 13);
		
		// textField_7
		textField_7 = new TextField();
		textField_7.setImmediate(false);
		textField_7.setWidth("100.0%");
		textField_7.setHeight("60px");
		gridLayout_1.addComponent(textField_7, 0, 14);
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Сохранить");
		button_1.setImmediate(true);
		button_1.setWidth("230px");
		button_1.setHeight("-1px");
		gridLayout_1.addComponent(button_1, 0, 16);
		gridLayout_1.setComponentAlignment(button_1, new Alignment(48));
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("Удалить");
		button_2.setImmediate(true);
		button_2.setWidth("230px");
		button_2.setHeight("-1px");
		gridLayout_1.addComponent(button_2, 0, 17);
		gridLayout_1.setComponentAlignment(button_2, new Alignment(48));
		
		// button_3
		button_3 = new Button();
		button_3.setCaption("Добавить нового");
		button_3.setImmediate(true);
		button_3.setWidth("230px");
		button_3.setHeight("-1px");
		gridLayout_1.addComponent(button_3, 0, 18);
		gridLayout_1.setComponentAlignment(button_3, new Alignment(48));
		
		// button_4
		button_4 = new Button();
		button_4.setCaption("Поиск");
		button_4.setImmediate(true);
		button_4.setWidth("230px");
		button_4.setHeight("-1px");
		gridLayout_1.addComponent(button_4, 0, 19);
		gridLayout_1.setComponentAlignment(button_4, new Alignment(48));
		
		return gridLayout_1;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_4() {
		// common part: create layout
		horizontalSplitPanel_4 = new HorizontalSplitPanel();
		horizontalSplitPanel_4.setImmediate(false);
		horizontalSplitPanel_4.setWidth("100.0%");
		horizontalSplitPanel_4.setHeight("100.0%");
		horizontalSplitPanel_4.setMargin(false);
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("100.0%");
		table_1.setHeight("100.0%");
		
		tableData.initProperties(table_1, new String[]{"ФИО", "Курс", "Группа", "Cпециализация", "Форма обучения", "e-mail", "Телефон"});
		tableData.fillTable(table_1, new String[][]{{"Рузе Анатолий Иванович", "1", "446", "Информатика", "Дневная", "anatosh@gmail.com", "458-32-44"}, {"Рудольф Виктор Германович", "3", "346", "Экономика", "Вечерняя", "anatoliy@gmail.com", "458-32-44"},
				{"Николаев Валерий Валентинович", "5", "446", "Логистика", "Вечерняя", "anatosh@gmail.com", "458-32-44"}, {"Андреенков Савелий Игнатьевич", "5", "846", "Юриспруденция", "Дневная", "anatosh@gmail.com", "458-32-44"}});
		
		horizontalSplitPanel_4.addComponent(table_1);
		
		// gridLayout_2
		gridLayout_2 = buildGridLayout_2();
		horizontalSplitPanel_4.addComponent(gridLayout_2);
		
		return horizontalSplitPanel_4;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_2() {
		// common part: create layout
		gridLayout_2 = new GridLayout();
		gridLayout_2.setImmediate(false);
		gridLayout_2.setWidth("100.0%");
		gridLayout_2.setHeight("100.0%");
		gridLayout_2.setMargin(true);
		gridLayout_2.setRows(35);
		
		// label_9
		label_9 = new Label();
		label_9.setImmediate(false);
		label_9.setWidth("-1px");
		label_9.setHeight("-1px");
		label_9.setValue("ФИО");
		gridLayout_2.addComponent(label_9, 0, 1);
		
		// textField_9
		textField_9 = new TextField();
		textField_9.setImmediate(false);
		textField_9.setWidth("100.0%");
		textField_9.setHeight("-1px");
		gridLayout_2.addComponent(textField_9, 0, 2);
		
		// label_10
		label_10 = new Label();
		label_10.setImmediate(false);
		label_10.setWidth("-1px");
		label_10.setHeight("-1px");
		label_10.setValue("Курс");
		gridLayout_2.addComponent(label_10, 0, 3);
		
		// textField_10
		textField_10 = new TextField();
		textField_10.setImmediate(false);
		textField_10.setWidth("100.0%");
		textField_10.setHeight("-1px");
		gridLayout_2.addComponent(textField_10, 0, 4);
		
		// label_11
		label_11 = new Label();
		label_11.setImmediate(false);
		label_11.setWidth("-1px");
		label_11.setHeight("-1px");
		label_11.setValue("Группа");
		gridLayout_2.addComponent(label_11, 0, 5);
		
		// textField_11
		textField_11 = new TextField();
		textField_11.setImmediate(false);
		textField_11.setWidth("100.0%");
		textField_11.setHeight("-1px");
		gridLayout_2.addComponent(textField_11, 0, 6);
		
		// label_12
		label_12 = new Label();
		label_12.setImmediate(false);
		label_12.setWidth("-1px");
		label_12.setHeight("-1px");
		label_12.setValue("Специализация");
		gridLayout_2.addComponent(label_12, 0, 7);
		
		// textField_12
		textField_12 = new TextField();
		textField_12.setImmediate(false);
		textField_12.setWidth("100.0%");
		textField_12.setHeight("-1px");
		gridLayout_2.addComponent(textField_12, 0, 8);
		
		// label_13
		label_13 = new Label();
		label_13.setImmediate(false);
		label_13.setWidth("-1px");
		label_13.setHeight("-1px");
		label_13.setValue("Форма обучения");
		gridLayout_2.addComponent(label_13, 0, 9);
		
		// textField_13
		textField_13 = new TextField();
		textField_13.setImmediate(false);
		textField_13.setWidth("100.0%");
		textField_13.setHeight("-1px");
		gridLayout_2.addComponent(textField_13, 0, 10);
		
		// label_14
		label_14 = new Label();
		label_14.setImmediate(false);
		label_14.setWidth("-1px");
		label_14.setHeight("-1px");
		label_14.setValue("E-mail");
		gridLayout_2.addComponent(label_14, 0, 11);
		
		// textField_14
		textField_14 = new TextField();
		textField_14.setImmediate(false);
		textField_14.setWidth("100.0%");
		textField_14.setHeight("-1px");
		gridLayout_2.addComponent(textField_14, 0, 12);
		
		// label_15
		label_15 = new Label();
		label_15.setImmediate(false);
		label_15.setWidth("-1px");
		label_15.setHeight("-1px");
		label_15.setValue("Телефон");
		gridLayout_2.addComponent(label_15, 0, 13);
		
		// textField_8
		textField_8 = new TextField();
		textField_8.setImmediate(false);
		textField_8.setWidth("100.0%");
		textField_8.setHeight("-1px");
		gridLayout_2.addComponent(textField_8, 0, 14);
		
		// button_6
		button_6 = new Button();
		button_6.setCaption("Сохранить");
		button_6.setImmediate(true);
		button_6.setWidth("230px");
		button_6.setHeight("-1px");
		gridLayout_2.addComponent(button_6, 0, 16);
		gridLayout_2.setComponentAlignment(button_6, new Alignment(48));
		
		// button_7
		button_7 = new Button();
		button_7.setCaption("Удалить");
		button_7.setImmediate(true);
		button_7.setWidth("230px");
		button_7.setHeight("-1px");
		gridLayout_2.addComponent(button_7, 0, 17);
		gridLayout_2.setComponentAlignment(button_7, new Alignment(48));
		
		// button_8
		button_8 = new Button();
		button_8.setCaption("Добавить нового");
		button_8.setImmediate(true);
		button_8.setWidth("230px");
		button_8.setHeight("-1px");
		gridLayout_2.addComponent(button_8, 0, 18);
		gridLayout_2.setComponentAlignment(button_8, new Alignment(48));
		
		// button_9
		button_9 = new Button();
		button_9.setCaption("Поиск");
		button_9.setImmediate(true);
		button_9.setWidth("230px");
		button_9.setHeight("-1px");
		gridLayout_2.addComponent(button_9, 0, 19);
		gridLayout_2.setComponentAlignment(button_9, new Alignment(48));
		
		return gridLayout_2;
	}
	
	
}
