package ru.reu_intro;

import java.util.ArrayList;
import java.util.Arrays;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;

public class docsBase extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private ComboBox comboBox_2;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private ComboBox comboBox_1;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Label label_5;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public docsBase() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("920px");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("920px");
		setHeight("100.0%");
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1,
				"top:1.0px;right:1.0px;bottom:1.0px;left:1.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("100.0%");
		gridLayout_1.setMargin(true);
		gridLayout_1.setColumns(15);
		gridLayout_1.setRows(10);
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("<h1>База документов</h1>");
		label_5.setContentMode(3);
		gridLayout_1.addComponent(label_5, 4, 0);
		gridLayout_1.setComponentAlignment(label_5, new Alignment(20));
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Тип документа");
		gridLayout_1.addComponent(label_1, 3, 2);
		
		// comboBox_1
		comboBox_1 = new ComboBox();
		comboBox_1.setImmediate(false);
		comboBox_1.setWidth("250px");
		comboBox_1.setHeight("-1px");
		comboboxData.fillCombobox(comboBox_1, new ArrayList<String>(Arrays.asList("Внешние","Внутренние")));
		gridLayout_1.addComponent(comboBox_1, 4, 2);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Сортировать по");
		gridLayout_1.addComponent(label_3, 3, 3);
		
		// comboBox_2
		comboBox_2 = new ComboBox();
		comboBox_2.setImmediate(false);
		comboBox_2.setWidth("250px");
		comboBox_2.setHeight("-1px");
		comboboxData.fillCombobox(comboBox_2, new ArrayList<String>(Arrays.asList("Семестрам","Годам")));
		gridLayout_1.addComponent(comboBox_2, 4, 3);
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("589px");
		label_4.setHeight("376px");
		label_4.setValue("<a href=\"http://www.rea.ru/UserFiles/654321/documents/%D0%9F%D0%A4%D0%A5%D0%94%20%D0%A0%D0%AD%D0%A3%20%D0%B8%D0%BC.%20%D0%93.%D0%92.%20%D0%9F%D0%BB%D0%B5%D1%85%D0%B0%D0%BD%D0%BE%D0%B2%D0%B0%20%D0%BD%D0%B0%202013-2015%20%D0%BE%D1%82%2015.02.2013.pdf\">План финансово-хозяйственной деятельности «РЭУ им. Г.В. Плеханова» на 2013-2015 от 15.02.2013</a><br><br> <a href=\"http://www.rea.ru/UserFiles/654321/documents/prikaz1928.pdf\">Приказ Федеральной службы по надзору в сфере образования и науки \"О государственной аккредитации Государственного образовательного учреждения \"Российская экономическая академия имени Г.В. Плеханова\" №1928 от 19 июля 2010г.</a><br><br>  <a href=\"http://www.rea.ru/UserFiles/654321/documents/prikaz26082010.pdf\">Приказ Министерства образования и науки Российской Федерации \"О переименовании Государственного образовательного учреждения высшего профессионального образования \"Российская экономическая академия имени Г.В. Плеханова\" и его филиалов\" № 883 от 26 августа 2010г.</a><br><br> <a href=\"http://www.rea.ru/UserFiles/654321/documents/%D0%9F%D1%80%D0%B8%D0%BA%D0%B0%D0%B7%20%D0%9C%D0%B8%D0%BD.%D0%9E%D0%B1%D1%80.%20%E2%84%962055%20%D0%BE%D1%82%2023%20%D0%B8%D1%8E%D0%BD%D1%8F%202011%D0%B3.pdf\">Приказ Министерства образования и науки Российской Федерации \"О реорганизации федерального государственного бюджетного учреждения высшего профессионального образования «Российский экономический университет имени Г.В. Плеханова» и Государственного образовательного учреждения дополнительного профессионального образования «Межотраслевой институт повышения квалификации и переподготовки руководящих кадров и специалистов Российской экономической академии им. Г.В. Плеханова» №2055 от 23 июня 2011г.</a><br><br>");
		label_4.setContentMode(3);
		gridLayout_1.addComponent(label_4, 4, 6);
		
		return gridLayout_1;
	}

}
