package ru.reu_intro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

public class information extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_2;
	@AutoGenerated
	private Panel panel_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Label label_6;
	@AutoGenerated
	private Panel panel_3;
	@AutoGenerated
	private VerticalLayout verticalLayout_4;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private Panel panel_4;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Label label_5;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public information() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet_2
		tabSheet_2 = buildTabSheet_2();
		mainLayout.addComponent(tabSheet_2, "left:10.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_2() {
		// common part: create layout
		tabSheet_2 = new TabSheet();
		tabSheet_2.setImmediate(true);
		tabSheet_2.setWidth("100.0%");
		tabSheet_2.setHeight("100.0%");
		
		// panel_4
		panel_4 = buildPanel_4();
		tabSheet_2.addTab(panel_4, "О факультете", null);
		
		// panel_3
		panel_3 = buildPanel_3();
		tabSheet_2.addTab(panel_3, "Библиотека", null);
		
		// panel_2
		panel_2 = buildPanel_2();
		tabSheet_2.addTab(panel_2, "Ссылки на ресурсы", null);
		
		return tabSheet_2;
	}

	@AutoGenerated
	private Panel buildPanel_4() {
		// common part: create layout
		panel_4 = new Panel();
		panel_4.setImmediate(false);
		panel_4.setWidth("100.0%");
		panel_4.setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		panel_4.setContent(verticalLayout_1);
		
		return panel_4;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(true);
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("95.0%");
		label_5.setHeight("-1px");
		label_5.setValue("<center><img src=\"http://autoussr.com/intranet/logo.png\" /></center><br>Миссия факультета математической экономики и информатики состоит в подготовке высококвалифицированных кадров, обладающих фундаментальными знаниями и современными компетенциями в сфере экономико-математического анализа и моделирования, статистической обработки данных, применения количественного инструментария обоснования управленческих решений, способных разрабатывать и внедрять сложные информационные и интеллектуально-аналитические системы в бизнесе и государственном секторе управления.  <br><br> Факультет математической экономики и информатики в рамках бакалавриата и магистратуры готовит выпускников, ориентированных на проведение аналитической и исследовательской работы, знающих и умеющих разрабатывать и применять современные математические методы и информационные технологии на различных уровнях управления экономикой, в том числе и в реальном секторе. <br><br> Система подготовки студентов базируется на глубоком изучении фундаментальных математических, экономических дисциплин и компьютерных технологий, овладение которыми позволяет нашим выпускникам получать квалификацию высочайшего уровня и возможность дальнейшего повышения уровня образования и профессионального роста. <br><br>  Подготовка студентов осуществляется на основе глубоко изучения трех блоков дисциплин: математических, информационных и экономических.");
		label_5.setContentMode(3);
		verticalLayout_1.addComponent(label_5);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private Panel buildPanel_3() {
		// common part: create layout
		panel_3 = new Panel();
		panel_3.setImmediate(false);
		panel_3.setWidth("100.0%");
		panel_3.setHeight("100.0%");
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		panel_3.setContent(verticalLayout_4);
		
		return panel_3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("95.0%");
		verticalLayout_4.setHeight("-1px");
		verticalLayout_4.setMargin(true);
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("95.0%");
		label_4.setHeight("-1px");
		label_4.setValue("Библиотека Российского экономического университета им. Г.В. Плеханова была основана в 1907 г. как библиотека Московского коммерческого института на базе книг, переданных институту из библиотеки Московского общества распространения коммерческого образования, и имела в своём фонде 123 издания. <br><br>Учебный комитет и Попечительский совет института уделяли формированию и пополнению фондов библиотеки самое пристальное внимание. Институт тратил существенные средства на покупку книг для библиотеки, что позволило увеличить фонд со 123 книг (на 1 января 1907 г.) до 51 892 (к 1914 г.). <br><br> Значительное место в притоке изданий занимали частные пожертвования. Основы фонда библиотеки составили труды основоположников экономической мысли, таких как: А. Смит, Д. Рикардо, К. Маркс, Ш. Фурье, М. И. Туган-Барановский, А. И. Герцен, Н. Г. Чернышевский, Ж.-Б. Сэй и др. В фонд редких изданий вошли коллекции книг преподавателей института: Я. Я. Никитинского, Н. С. Лунского, В. В. Шарвина, А. Ф. Фортунатова, Н. В. Шилова, П. А. Покровского, М. Я. Герценштейна, В. А. Краснокутского и др. Самая древняя книга в фонде - труды нидерландского философа Липсия на латыни - датирована 1613 годом. Она из библиотеки Д. Н. Егорова - преподавателя всеобщей истории Московского коммерческого института. <br><br> Не обходили вниманием библиотеку института государственные и общественные учреждения и организации. Министерство финансов, Министерство торговли и промышленности. Учитывая, что Московский коммерческий институт в первую очередь готовит специалистов для их отраслей, в обязательном порядке присылали в библиотеку института все свои печатные издания: отчеты, протоколы заседаний, статистические справочники и т.п. Считали своим долгом пополнить библиотеку городские и земские организации, а также редакции газет и журналов.");
		label_4.setContentMode(3);
		verticalLayout_4.addComponent(label_4);
		
		return verticalLayout_4;
	}

	@AutoGenerated
	private Panel buildPanel_2() {
		// common part: create layout
		panel_2 = new Panel();
		panel_2.setImmediate(false);
		panel_2.setWidth("100.0%");
		panel_2.setHeight("100.0%");
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		panel_2.setContent(verticalLayout_3);
		
		return panel_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(true);
		
		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("-1px");
		label_6.setHeight("-1px");
		label_6.setValue("Группа Вконтакте<br>Библиотека РЭУ им. Плеханова<br>Группа Фейсбук");
		label_6.setContentMode(3);
		verticalLayout_3.addComponent(label_6);
		
		return verticalLayout_3;
	}

}
